### ISSUE TITLE
RestSampler fails to work with Http Header Manager?

### ISSUE THREAD

**Issue by emicklei** [smartrics/JMeterRestSampler#1]
This observation is based on a strack trace in jmeter.log that says it cannot perform the default headers  setup 

jmeter.threads.JMeterThread: Test failed! java.lang.NoSuchMethodError: smartrics.jmeter.sampler.RestSampler.setDefaultRequestHeaders(Lorg/apache/commons/httpclient/HttpMethod;)V

(i am using 2.5)

**Comment by smartrics** [comment]
hi, the sampler has been tested with jmeter 2.3.4 - it's entirely possible that newest version of jmeter may not work.
i wonder if in this case the issue is caused by commons httpclient 3.1 not being in the classpath anymore? 
let me know if you find a solution or you're willing to contribute a fix. i'll be more than happy to merge it in

fabrizio

**Comment by smartrics** [comment]
actually - there seems to be a fork that has been updated to work with jmeter 2.5 
check opaopa6969 / JMeterRestSampler

**Comment by emicklei** [comment]
Thanx, I will have a look at this fork

On Thu, Sep 15, 2011 at 10:29 PM, Fabrizio Cannizzo <
reply@reply.github.com>wrote:

> actually - there seems to be a fork that has been updated to work with
> jmeter 2.5
> check opaopa6969 / JMeterRestSampler
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/smartrics/JMeterRestSampler/issues/1#issuecomment-2108830

## 

^ Ernest Micklei

6hoek.com - Bekijk, beoordeel en bestel bij bol.com . Tablet web applicatie,
uitgelicht op blog.6hoek.com

**Comment by smartrics** [comment]
no problems
